<?php

namespace Project\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository implements AjaxSearchInterface
{

    /**
     * @param      $terms
     *
     *
     * @return \Doctrine\ORM\Query
     */
    public function search($terms)
    {
        $qb = $this->createQueryBuilder("city");

        if (is_numeric($terms)) {
            $qb->where("city.cp = :cp");
            $qb->setParameter("cp", $terms);

            return $qb;
        }

        foreach (explode(" ", $terms) as $index => $term) {
            $qb->orWhere("city.name like :term".$index);
            if (is_numeric($term)) {
                $qb->orWhere("city.cp = :npa".$index);
                $qb->setParameter("cp".$index, $term);
            }
            $qb->setParameter("term".$index, "%".$term."%");
        }

        return $qb->getQuery();
    }
}
