<?php

namespace Project\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumPostRepository extends EntityRepository implements AjaxSearchInterface
{


    /**
     * @param string $slug
     *
     * @return Query
     */
    public function findByForumName(string $slug)
    {
        $sql =
            "SELECT p, u, r FROM %s p 
              JOIN p.forum f 
              JOIN p.user u 
              LEFT JOIN p.responses r 
              WHERE f.slug = :name
              ORDER BY p.updatedAt DESC";
        $dql = sprintf($sql, $this->getClassName());

        $query = $this->_em->createQuery($dql)->setParameter('name', $slug);

        return $query;
    }

    /**
     * @param          $terms
     *
     * @return QueryBuilder
     */
    public function search($terms)
    {
        $qb = $this->createQueryBuilder("post");

        if (is_numeric($terms)) {
            $qb->where("post.id= :id");
            $qb->setParameter("id", $terms);

            return $qb;
        }

        foreach (explode(" ", $terms) as $index => $term) {
            $qb->orWhere("post.title like :term");
            if (is_numeric($term)) {
                $qb->orWhere("post.id = :id");
                $qb->setParameter("id", $term);
            }
            $qb->setParameter("term", "%".$term."%");
        }

        return $qb->getQuery();
    }
}
