<?php

namespace Project\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Project\FrontBundle\Entity\News;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    /**
     * @return array|News[]
     */
    public function findActive()
    {
        $sql   = "SELECT n, c, a FROM %s n JOIN n.category c JOIN n.author a WHERE n.enabled = true";
        $query = $this->_em->createQuery(sprintf($sql, $this->getClassName()));

        return $query->getResult();
    }

    /**
     * @param string $slug
     *
     * @return mixed
     */
    public function findOneNewsDisplay(string $slug)
    {
        $sql   =
            "SELECT n, c, a, com FROM %s n 
              JOIN n.category c 
              JOIN n.author a
              LEFT JOIN n.comments com 
            WHERE n.enabled = true 
              AND n.slug = :slug";
        $query = $this->_em->createQuery(sprintf($sql, $this->getClassName()))->setParameter('slug', $slug);
        $query->setMaxResults(1);

        return $query->getOneOrNullResult();
    }
}
