<?php

namespace Project\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Project\FrontBundle\Entity\ForumPost;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostResponseRepository extends EntityRepository
{
    /**
     * @param string    $forum
     * @param ForumPost $post
     *
     * @return Query
     */
    public function findResponseByPost(string $forum, ForumPost $post)
    {
        $sql =
            'SELECT r, p, ru, c FROM %s r 
              JOIN r.post p 
              JOIN p.forum f 
              JOIN r.user ru 
              LEFT JOIN r.childs c
            WHERE r.parent IS NULL AND  p = :post AND f.slug = :forum';

        $dql   = sprintf($sql, $this->getClassName());
        $query = $this->_em->createQuery($dql)->setParameter('post', $post)->setParameter('forum', $forum);

        return $query;

    }

    /**
     * @param          $terms
     *
     * @return QueryBuilder
     */
    public function search($terms)
    {
        $qb = $this->createQueryBuilder("response");

        if (is_numeric($terms)) {
            $qb->where("response.id= :id");
            $qb->setParameter("id", $terms);

            return $qb;
        }

        foreach (explode(" ", $terms) as $index => $term) {
            $qb->orWhere("response.message like :term");
            if (is_numeric($term)) {
                $qb->orWhere("response.id = :id");
                $qb->setParameter("id", $term);
            }
            $qb->setParameter("term", "%".$term."%");
        }

        return $qb->getQuery();
    }
}
