<?php

namespace Project\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TakenParticipateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TakenParticipateRepository extends EntityRepository
{
}
